@startuml HRS_オブジェクト図
' ホテル予約システム オブジェクト図（ある時点のインスタンス）最新版
skinparam objectAttributeIconSize 0
skinparam shadowing false
title オブジェクト図（2名が宿泊中のスナップショット）

object "利用者1 : 利用者" as u1 {
  利用者名 = たける
}
object "利用者2 : 利用者" as u2 {
  利用者名 = じゅん
}

object "予約1 : 予約" as r1 {
  予約番号 = 1001
  チェックイン日 = 2026/06/26
  状態 = 宿泊中
}
object "予約2 : 予約" as r2 {
  予約番号 = 1002
  チェックイン日 = 2026/06/26
  状態 = 宿泊中
}

object "部屋1 : シングル" as rm1 {
  部屋番号 = 101
  基本宿泊料 = 6000
}
object "部屋2 : ダブル" as rm2 {
  部屋番号 = 201
  基本宿泊料 = 8000
}

object "宿泊1 : 宿泊" as s1 {
  イン日時 = 2026/06/26
  アウト日時 = 2026/06/27
}
object "宿泊2 : 宿泊" as s2 {
  イン日時 = 2026/06/26
  アウト日時 = 2026/06/27
}

object "支払い1 : 支払い" as p1 {
  支払い料金 = 6000
}
object "支払い2 : 支払い" as p2 {
  支払い料金 = 8000
}

object "受付係 : ホテル受付係" as recep {
  名前 = そういちろう
}

u1 -- r1 : 予約する
u2 -- r2 : 予約する
r1 -- rm1 : 対象
r2 -- rm2 : 対象
rm1 -- s1 : 記録
rm2 -- s2 : 記録
r1 -- s1
r2 -- s2
s1 -- p1 : 精算
s2 -- p2 : 精算
recep -- s1 : 対応
recep -- s2 : 対応
@enduml
