@startuml HRS_コラボレーション図_予約キャンセル

left to right direction
skinparam shadowing false
title コラボレーション図：予約をキャンセルする（★演習6）

actor "利用者" as U

boundary "予約キャンセル画面" as B
control "予約キャンセル制御" as C
entity "予約" as R
entity "部屋" as RM

U --> B : 1: 予約番号を入力する(予約番号)
B --> C : 2: 予約を検索する(予約番号)
C --> R : 3: 予約詳細を取得する()
U --> B : 4: キャンセルを確定する()
B --> C : 5: 予約キャンセルを完了する(予約番号)
C --> R : 6: 状態を「キャンセル」にする()
C --> RM : 7: 部屋を空室にする()

@enduml
